### ISSUE TITLE
TODO: 2023 Release

### ISSUE THREAD

**Issue by calum-chamberlain** [calum-chamberlain/ESCI451-Python#31]
ESCI451 2023 is rapidly approaching. There are a few things to do before we are ready:
- [x] Issue #30 - migrate to jupyter-lab. This is mostly complete, but some tweaks to plotting need to be made
- [x] Issue #29 - evaluate seaborn - I have added a note and links to customising seaborn plots.
- [x] Issue #25 - test with more Taupō data files
- [x] Issue #24 
- [x] Issue #21 - I think this fill be solved in #30, but need to check
- [x] Issue #6:
   - [x] 2B - make it explicit that NZ region should be selected
   - [x] module 3A - [comment by FIK](https://github.com/calum-chamberlain/ESCI451-Python/issues/6#issuecomment-1062204286)
   - [x] Module 3B: suppress warnings in `PairGrid`
   - [x] Include reading of excel sheets
   - [x] Include skipping of rows and footer when reading
   - [x] Include dropna and fillna methods
   ~~- [ ] *possible* example of plotting NZAFD~~ *skipping for 2023 - getting data programmatically too hard.*
   - [x] Introduce reading Python error messages in module 1A
- [x] Check all links
- [x] Add final module with some notes on python scripting and running from command line
- [x] Check tests pass
- [x] Check manually on linux
- [x] Check manually on MacOS - @FinniganIK can you do this please?
- [x] Check manually on Windows
- [x] Make 2023 branch & clear outputs & release
- [x] Get Aleks to update the environment on our systems
